server:
  port: 18889

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
logging:
  level:
    com.laoyin.maven: DEBUG
    org.springframework.jdbc: DEBUG